name: Bug Reproduction - Rustup Target Add

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  rustup-target-add:
    runs-on: ubuntu-latest
    name: "Method 1: Manual rustup target add (should work)"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
          use-cache: false

      - name: Setup Rust (without ARM64 target)
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-lambda
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-lambda

      - name: Show initial state
        run: |
          echo "=== Initial State ==="
          echo "Rust targets installed:"
          rustup target list --installed
          echo "Cargo version: $(cargo --version)"
          echo "Zig version: $(zig version)"
          echo "Cargo lambda version: $(cargo lambda --version)"

      # - name: Manually add ARM64 target with rustup
      #   run: |
      #     echo "=== Manually adding aarch64-unknown-linux-gnu target ==="
      #     rustup target add aarch64-unknown-linux-gnu

      # - name: Verify target was added
      #   run: |
      #     echo "=== Verifying aarch64-unknown-linux-gnu target installation ==="
      #     rustup target list --installed | grep aarch64-unknown-linux-gnu || echo "Target NOT found!"

      - name: Build with manually added target
        run: |
          echo "=== Building with manually added target ==="
          cargo lambda build --release --arm64

      - name: Verify build success
        run: |
          echo "=== Build Results ==="
          find target -name "bootstrap*" -type f || echo "No bootstrap files found"
